### ISSUE TITLE
scale effect is not smooth

### ISSUE THREAD

**Issue by ChanceTheHacker** [universal-tilt-js/react-universal-tilt#2]
Hello again. Thank you for such a quick fix with the readme before, I've found a new bug now.  It seems the scale effect is not working as intended. Scale seems to grow in 2 jerking steps sometimes, and grow larger than intended. I believe it is getting scaled twice in some cases.  I think if you set scale to 1.3 for example, that it grows to 1.3x the size and then does it again immediately afterwards.  A few times I actually had my item scale a third or fourth time and completely cover the screen.

I seem to get this bug more often when I use scale in conjunction with reverse but I still seem to get it no matter what the case. here is my code to perhaps help recreate the bug. I wish I could fix it myself and submit a fix, but sadly I'm just not skilled enough to read the functions and understand whats happening. I've tried several times, and it's just above my current skill level.

```
import React, { Component } from 'react';
import './card.css';
import ReactTilt from 'react-universal-tilt';

export default class WishListCard extends Component{

 render(){
	return (
		<div id="card-container">
			<ReactTilt options={{
				reverse: true,
				scale: 1.3,
				shine: true
			}} className="wl-card">
			 	
	 		</ReactTilt>
		 	<ReactTilt>
			 	<div className="wl-card">
			 		
			 	</div>
		 	</ReactTilt>
		 	<ReactTilt>
			 	<div className="wl-card">
			 		
			 	</div>
		 	</ReactTilt>
		</div>
	)
  }
}
```

and the css

```
#card-container {
	width: 100%;
	height: 64.9vh;
	display: flex;
	flex-direction: row;
	justify-content: space-around;
}


.wl-card {
	background: white;
	border: 2px solid black;
	border-radius: 10px;
	height: 60vh;
	width: 25vw;
}
```

**Comment by JB1905** [comment]
I compared the size of the element using the scale option and the scaled element in CSS. The size is identical. In the demo, the scale option suggests 1.3. The description has not been updated and this item has a scale of 1.2. For large objects, I suggest using an intermediate scale, e.g. 1.06. The performance of the animation depends on the value of the speed, max, perspective and easing options.

[List of available options with description](https://github.com/JB1905/universal-tilt.js#options)

**Comment by WCPeragine** [comment]
Ok, I will look into it more. Although this does not explain the bug I got in which the ReactTilt container grew to a size greater than the entire screen. I have not been able to replicate it though, so I can't figure out why it is doing it. All I know is that very occasionally, my car element would grow to be much larger than the full screen size.

**Comment by WCPeragine** [comment]
Ok after quite a lot of experimentation, I have found what is causing the actual issue. The problem is moving the mouse inside the <ReactTilt> container. For example, if I move my mouse inside the bounds of the container the transition is smooth and there are no issues. However, if I enter the bounds with my mouse and continue to quickly move the mouse around inside the container and do not stop, no transition will occur at all. after the amount of time determined by the speed option, it will just immediately move from scale 1 to whatever the setting is with out any transition animation.

**Comment by JB1905** [comment]
In what browser the problem appears. I checked the smoothness of animations in **Chrome, Firefox, Opera and Safari**, and everything seems to be running smoothly. Animation depends mainly on the **speed** and **easing** options. If the problem exists and I don't see it, it is [here](https://github.com/JB1905/universal-tilt.js), because the react-universal-tilt options are passed directly to universal-tilt.js.

**Comment by WCPeragine** [comment]
I'm using chrome browser on an arch linux os. later today I will download a screen cast program and make a gif of the issue to show you the problem.

should I move this issue to the universal-tilt.js repository than instead of having it open here?

**Comment by JB1905** [comment]
react-universal-tilt only implements universal-tilt.js (written in Vanilla JS and jQuery support) as a component. I suggest moving the bug report to the universal-tilt.js repository.

**Comment by JB1905** [comment]
The screen recording will be very useful

**Comment by WCPeragine** [comment]
ok, I will do so.
